### PR TITLE
allow configuring the PROCESS option via the config file

### LINKED ISSUE #27: Allow setting PROCESS option via trace file
The documentation says:

> Please note that you **cannot** register the profiler itself via the settings file, and you **cannot** set the `PROCESS` option via the settings file.

While the former makes sense, the latter doesn't. We should allow this.

### PR DESCRIPTION
**Pull request by karottenreibe**
Fixes #27 

- [ ] Tests written
- [x] Documentation updated

### CODE REVIEW

**Comment by karottenreibe** [comment]
rfr

**Comment by karottenreibe** [comment]
sorry, not yet rfr

**Comment by karottenreibe** [comment]
still need to test changes before merging

**Comment by salsolatragus** [comment]
It seems this change became obsolete with the Yaml-config change, didn't it?

**Pull request closed without merging**
