### PR TITLE
handle unclean shutdown of profiler

### LINKED ISSUE #38: Shutdown sometimes not called
In this case we lose all coverage. Seems to be expected behavior:

https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/ms230217(v%3dvs.100)

### PR DESCRIPTION
**Pull request by karottenreibe**
Fixes #38 

- [ ] Tests written (tested manually against problematic app)
- [ ] Documentation updated (not needed)

### CODE REVIEW

**Comment by karottenreibe** [comment]
rfr @zipperle

**Comment by zipperle** [comment]
@karottenreibe can you resolve the merge conflict?

**Comment by salsolatragus** [comment]
@zipperle @karottenreibe I've resolved the merge conflict. Can we get this closed? Would help us at MR 😇

**Comment by karottenreibe** [comment]
@zipperle could you review this? I'm fully booked already next week, I fear I won't have time :-(

**Comment by salsolatragus** [comment]
@karottenreibe it's your work anyways, so you shouldn't review it ;) I could do the review, if this is fine with you both (I assume that resolving the merge conflict doesn't disqualify me as a reviewer).

**Comment by karottenreibe** [comment]
fine with me, but I won't be able to rework it next week, so either @zipperle jumps in or you'll have to wait for the week after :-( Maybe you two can discuss this and if you'd like me to do the rework, send me a short mail and I'll block time the week after :-)

**Pull request merged**
